[workspace]
members = [
    "crates/circuits/greco",
    "crates/circuits/pvss/pk_pvw",
    "crates/circuits/pvss/pk_trbfv",
    "crates/circuits/pvss/sk_shares",
    "crates/libs/safe/",
    "crates/libs/polynomial"
]
